"""File operation request/response validation schemas.

Pydantic v2 models for S3-backed file upload, download (presigned URL),
and deletion endpoints. All request models enforce strict mode to reject
unexpected fields.

Used by:
    app/routes/files.py — Files Blueprint route handlers
    app/services/file_service.py — S3 file operations service
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class FileUploadRequest(BaseModel):
    """Request metadata model for POST /api/files/upload.

    Validates metadata accompanying a multipart file upload.
    The actual file binary is handled via Flask's ``request.files``,
    not through this Pydantic model.  This validates the optional
    metadata fields that may accompany the upload form data.

    Attributes:
        description: Optional human-readable description of the uploaded file.
        tags: Optional list of string tags for file categorization and search.
        folder: Optional S3 folder/prefix path for organizing files within
            the bucket (e.g. ``"reports/2026/q1"``).

    Notes:
        ``model_config = ConfigDict(strict=True)`` rejects any fields not
        explicitly defined on this model, per AAP §0.7.3.
    """

    model_config = ConfigDict(strict=True, extra="forbid")

    description: str | None = Field(
        None,
        max_length=1000,
        description="Optional description of the uploaded file",
    )
    tags: list[str] | None = Field(
        default=None,
        description="Optional tags for file categorization",
    )
    folder: str | None = Field(
        None,
        max_length=500,
        description="Optional S3 folder/prefix path for organizing the file",
    )


class FileUploadResponse(BaseModel):
    """Response model for POST /api/files/upload.

    Returned after a successful file upload to S3.  Contains the S3
    object key and associated metadata about the uploaded file.

    Attributes:
        key: The S3 object key — the unique identifier within the bucket
            (e.g. ``"uploads/abc123/report.pdf"``).
        filename: The original filename as provided by the client.
        content_type: MIME type of the uploaded file (e.g. ``"application/pdf"``).
        size_bytes: File size in bytes (non-negative when present).
        bucket: The S3 bucket name where the file was stored.
        url: Direct URL to the uploaded file, if publicly accessible.
        uploaded_at: UTC timestamp recording when the upload completed.
        uploaded_by: The Auth0 user ID (``sub`` claim) of the uploader.

    Notes:
        ``model_config = ConfigDict(strict=False)`` — response models are
        lenient to accommodate varying data shapes from service layer.
    """

    model_config = ConfigDict(strict=False)

    key: str = Field(
        ...,
        description="S3 object key (unique identifier for the uploaded file)",
    )
    filename: str = Field(
        ...,
        description="Original filename from the upload",
    )
    content_type: str | None = Field(
        None,
        description="MIME type of the uploaded file",
    )
    size_bytes: int | None = Field(
        None,
        ge=0,
        description="File size in bytes",
    )
    bucket: str = Field(
        ...,
        description="S3 bucket name where the file was stored",
    )
    url: str | None = Field(
        None,
        description="Direct URL to the uploaded file (if publicly accessible)",
    )
    uploaded_at: datetime | None = Field(
        None,
        description="Upload timestamp (UTC)",
    )
    uploaded_by: str | None = Field(
        None,
        description="User ID who uploaded the file (from JWT sub claim)",
    )


class FileDownloadResponse(BaseModel):
    """Response model for GET /api/files/<key>.

    Returns a presigned S3 download URL for secure, time-limited file
    access.  The presigned URL is generated by boto3 and has a
    configurable TTL (``expires_in`` seconds).

    Attributes:
        key: The S3 object key identifying the file.
        filename: The original filename, if available in object metadata.
        download_url: The presigned S3 URL — clients use this to download
            the file directly from S3 without further authentication.
        expires_in: Number of seconds until the presigned URL expires.
            Defaults to 3600 (1 hour).
        content_type: MIME type of the file, if known.
        size_bytes: File size in bytes (non-negative when present).

    Notes:
        No direct S3 bucket credentials are exposed to the client; all
        access is mediated through the presigned URL.
    """

    model_config = ConfigDict(strict=False)

    key: str = Field(
        ...,
        description="S3 object key",
    )
    filename: str | None = Field(
        None,
        description="Original filename",
    )
    download_url: str = Field(
        ...,
        description="Presigned S3 download URL (time-limited)",
    )
    expires_in: int = Field(
        3600,
        description="URL expiration time in seconds (default: 3600 = 1 hour)",
    )
    content_type: str | None = Field(
        None,
        description="MIME type of the file",
    )
    size_bytes: int | None = Field(
        None,
        ge=0,
        description="File size in bytes",
    )


class FileDeleteResponse(BaseModel):
    """Response model for DELETE /api/files/<key>.

    Confirms deletion of a file from S3.  The ``deleted`` flag
    indicates success, and ``message`` provides a human-readable status.

    Attributes:
        key: The S3 object key that was deleted.
        deleted: Boolean indicating whether the deletion succeeded.
        message: Human-readable status message describing the outcome.
        deleted_at: UTC timestamp recording when the deletion occurred.

    Notes:
        S3 ``delete_object`` is idempotent — deleting a non-existent key
        does not raise an error.  The service layer may still return
        ``deleted=True`` in that scenario per S3 semantics.
    """

    model_config = ConfigDict(strict=False)

    key: str = Field(
        ...,
        description="S3 object key that was deleted",
    )
    deleted: bool = Field(
        True,
        description="Whether the file was successfully deleted",
    )
    message: str = Field(
        "File deleted successfully",
        description="Human-readable status message",
    )
    deleted_at: datetime | None = Field(
        None,
        description="Deletion timestamp (UTC)",
    )
